### ISSUE TITLE
MonteCarlo Tree documentation

### ISSUE THREAD

**Issue by flobe99** [flobe99/wis_project#7]

**Comment by steve-ballmer-developer** [comment]
LATENT ACTION MCTS

A latent action monte carlo tree search splits the search space into a high- and a low-performing region. This is done by sampling over the search space and then applying a k-means algorithm(k=2). a svm then learns the boundary.
This results in an node of a monte carlo tree being split. If this is done recursively, it results in a tree with the highest-performing region on the leftmost leaf

**Comment by steve-ballmer-developer** [comment]
MONTE CARLO TREE SEARCH

a monte carlo tree consists of different leaves representing certain states. the goal here is to find
a monte carlo tree search consists if 5 steps:
1. select
when in a given state, it is decided what action to take to get to a different state based on a policy
2. expand
when the current leaf has no children some actions are taken which lead to different states
3. simulate
the reward for the expanded states is simulated
4. backpropagation
if the new reward is greater than existing ones, all parent nides are updated
